require('../../../node_modules/html5-boilerplate/dist/js/vendor/modernizr-3.6.0.min.js')
window.Popper = require('popper.js').default

window._ = require('lodash')
window.$ = window.jQuery = require('jquery')
require('./nav-toggle-navigator.js')(window.document, window.$cookies)
require('../../../node_modules/html5-boilerplate/dist/js/plugins.js')
window.FastClick = require('fastclick')
window.FastClick(document.body)
window.toastr = require('toastr')
window.moment = require('moment')
require('jquery-slimscroll')
require('jquery.easing')
require('@coreui/coreui-plugin-chartjs-custom-tooltips/dist/js/custom-tooltips.min.js')
require('datatables.net-bs4')
require('select2')
require('tempusdominus-bootstrap-4')
require('./common-function.js')(window)
require('./common-validation.js')(window)
require('./nav-toggle-recorder.js')(window, window.jQuery, window.$cookies)
